name: Create Tar Gz

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Tar Gz
      run: |
       touch action-tutorial.tar.gz
       tar -czf action-tutorial.tar.gz --exclude=action-tutorial.tar.gz .
      working-directory: ${{ github.workspace }}

   
      
      


