name: Release sha256

on:
  push:
    branches:
      - main  

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Generate sha256sum
      run: |
       echo shasum -a 256 > sha256sum.txt  # Replace with your sha256sum generation command
       git add sha256sum.txt
       git commit -m "Add sha256sum.txt"
       git push

